name: FallingApples
main: me.miniblacktw.fallingapples.Main
version: 1.0
api-version: 1.21
author: miniblack_Tw
commands:
  fallingapples:
    description: Manage Main settings
    usage: §c/fallingapples < bypass | unbypass > <player>
    permission: fallingapples.cmd
    permission-message: §cYou don't have permission
permissions:
  fallingapples.cmd:
    description: Access to enable/disable a player's bypass
    default: op